### ISSUE TITLE
Switch from `cups-config` to `pkg-config`

### ISSUE THREAD

**Issue by Pandapip1** [OpenPrinting/braille-printer-app#8]
`braille-printer-app` uses `cups-config` to find CUPS instead of `pkg-config`. `cups-config` is removed in `libcups`.

**Comment by sthibaul** [comment]
Ok, but how can we get `$CUPS_DATADIR`, `$CUPS_SERVERROOT`, `$CUPS_SERVERBIN` from pkg-config? `cups3.pc` doesn't seem to be exposing them...

**Comment by michaelrsweet** [comment]
@sthibaul Those values are not used for CUPS 3.x.

They *are* available with the CUPS 2.x pkg-config file (cups.pc) using the "--variable=..." option, e.g.:

```
pkg-config --variable=cups_datadir cups
pkg-config --variable=cups_serverbin cups
pkg-config --variable=cups_serverroot cups
```

That said, I'm not sure why you would need these values in a printer application?

**Comment by sthibaul** [comment]
the braille-printer-app is still halfway into being a printer application

**Comment by sthibaul** [comment]
I don't see these variables in cups.pc from version 2.4.10

**Comment by tillkamppeter** [comment]
Note that said directories are usually not needed by a Printer Application. A Printer Application should be installable independent of a CUPS (2.x) daemon/environment. It should not be based on installed CUPS filters. For getting the functionality of filters provided by CUPS or by cups-filters, use the filter functions of libcupsfilters, for filters which are part of the braille-printer-app repo, as long as they are separate executables, if no local CUPS environment is discovered, put them into `/usr/lib/braille-printer-app/filter/` for example.

**Comment by tillkamppeter** [comment]
> Note that said directories are usually not needed by a Printer Application. A Printer Application should be installable independent of a CUPS (2.x) daemon/environment. It should not be based on installed CUPS filters. For getting the functionality of filters provided by CUPS or by cups-filters, use the filter functions of libcupsfilters, for filters which are part of the braille-printer-app repo, as long as they are separate executables, if no local CUPS environment is discovered, put them into `/usr/lib/braille-printer-app/filter/` for example.

See #11 .
